Fix and add jstr_test.sh to make test
The script was broken due to files and paths that are not found here but
are found in mkiocccentry repo (where this originated) but since make
test did not run it it was not detected.

This commit shows more than ever that a new script is needed to run all
the different tests like the mkiocccentry repo does. This commit and the
previous commit do cause problems with make test in that repo and
workarounds/fixes will have to be introduced here to solve those
problems.

diff --git a/test_jparse/Makefile b/test_jparse/Makefile
--- a/test_jparse/Makefile
+++ b/test_jparse/Makefile
@@ -422,6 +422,10 @@ test:
 	    echo "${OUR_NAME}: ERROR: executable not found: ./jparse_test.sh" 1>&2; \
 	    echo "${OUR_NAME}: ERROR: unable to perform complete test" 1>&2; \
 	    exit 1; \
+	elif [[ ! -x ./jstr_test.sh ]]; then \
+	    echo "${OUR_NAME}: ERROR: executable not found: ./jstr_test.sh" 1>&2; \
+	    echo "${OUR_NAME}: ERROR: unable to perform complete test" 1>&2; \
+	    exit 1; \
 	else \
 	    echo "./jparse_test.sh -j ./jparse -p test_jparse/pr_jparse_test -d test_jparse/test_JSON -s . test_jparse/json_teststr.txt"; \
 	    ./jparse_test.sh -j ./jparse -p test_jparse/pr_jparse_test -d test_jparse/test_JSON -s . test_jparse/json_teststr.txt; \
@@ -440,6 +444,14 @@ test:
 		exit "$$EXIT_CODE"; \
 	    else \
 		echo ${OUR_NAME}: "PASSED: jparse_test.sh"; \
+	    fi; \
+	    ./jstr_test.sh 2>&1; \
+	    EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then \
+		echo "${OUR_NAME}: ERROR: jstr_test.sh failed, error code: $$EXIT_CODE"; \
+		exit "$$EXIT_CODE"; \
+	    else \
+		echo ${OUR_NAME}: "PASSED: jstr_test.sh"; \
 	    fi; \
 	fi
 	${S} echo
