Improve test_jparse/jparse_test.sh
Added option -F which says that the files passed on the command line are
to be checked as full JSON documents, not blobs per line.

diff --git a/test_jparse/Makefile b/test_jparse/Makefile
--- a/test_jparse/Makefile
+++ b/test_jparse/Makefile
@@ -437,6 +437,16 @@ test:
 		echo "${OUR_NAME}: PASSED: jparse_test.sh"; \
 	    fi; \
 	    echo; \
+	    echo "${OUR_NAME}: RUNNING:  ./jparse_test.sh -v ${VERBOSITY} -j ./jparse -F jparse.json"; \
+	    ./jparse_test.sh -v ${VERBOSITY} -j ./jparse -F jparse.json; \
+	    EXIT_CODE="$$?"; \
+	    if [[ $$EXIT_CODE -ne 0 ]]; then \
+		echo "${OUR_NAME}: ERROR: jparse_test.sh failed, error code: $$EXIT_CODE"; \
+		exit "$$EXIT_CODE"; \
+	    else \
+		echo "${OUR_NAME}: PASSED: jparse_test.sh"; \
+	    fi; \
+	    echo; \
 	    echo "${OUR_NAME}: RUNNING: ./jparse_test.sh -v ${VERBOSITY} -f -j ./jparse test_jparse/json_teststr_fail.txt"; \
 	    ./jparse_test.sh -v ${VERBOSITY} -f -j ./jparse test_jparse/json_teststr_fail.txt >/dev/null 2>&1; \
 	    EXIT_CODE="$$?"; \
